version: "3.0"

services:

  backend:
    build:
      context: ./backend
    container_name: "backend"
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env
    ports:
        - '80:8080'
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  mail-service:
    build:
      context: ./mail-sender
    container_name: "mail-service"
    depends_on:
      - rabbitmq
    env_file:
      - .env
    ports:
      - '8082:8082'
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  postgres:
    image: postgres:14-alpine
    container_name: hd_postgres
    environment:
      POSTGRES_DB: "hd_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/var/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.8.9-management
    container_name: hd_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 1111
    ports:
      - "15672:15672"
      - "5672:5672"