FROM maven:3.8.5-openjdk-17 AS build-backend
WORKDIR /backend
COPY backend/src /backend/src
COPY backend/pom.xml /backend/
COPY --from=build-rabbit /common-rabbit /backend/common-rabbit
WORKDIR /backend
RUN mvn -f /backend/pom.xml clean package