drop table if exists organization cascade;

create table organization
(
    id          int8 GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(255) UNIQUE NOT NULL,
    description varchar(1000)       NOT NULL,
    active      boolean default false,
    owner_id    int8 UNIQUE,
    participants_max_count int CHECK ( participants_max_count >= 0 ),
    country varchar(255),
    region varchar(255),
    city varchar(255),
    address varchar(500),
    type varchar(50),
    primary key (id)
);