drop table if exists user_activation_code;

create table user_activation_code(
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
  code varchar(255) UNIQUE NOT NULL,
  user_id int8
);

CREATE INDEX idx_user_activation_code_code ON user_activation_code (code);