spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/hd_db
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    username: user
    password: 1111

