name: HD CI Maven
on:
  push:
    branches: [ "test-wf" ]
  pull_request:
    branches: [ "test-wf" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and test common-rabbit
        run: mvn -B clean package install --file pom.xml
      - name: Build and test backend
        run: mvn -B clean package install --file backend/pom.xml
      - name: Build and test mail service
        run: mvn -B clean package install --file mail-sender/pom.xml

